src/objects/Out_Of_Office__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Out_Of_Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Out Of Office</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Out Of Office Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Out Of Office</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testOOOTrigger.cls
@isTest
private class testOOOTrigger {

    public static testMethod void testOOONotification() {
    	Profile p = [select id from profile where name='Standard User'];
    	User u = new User(	alias = 'standt', email='standarduser@testorg.com',
							emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
							localesidkey='en_US', profileid = p.Id,
							timezonesidkey='America/Los_Angeles', username='testOOOTrigger@testorg.com');
    	insert u;					

    	User u2 = new User(	alias = 'standt2', email='standarduser2@testorg.com',
							emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
							localesidkey='en_US', profileid = p.Id,
							timezonesidkey='America/Los_Angeles', username='testOOOTrigger2@testorg.com');
    	insert u2;					
    	
    	Out_Of_Office__c newOOO = new Out_Of_Office__c (user__c = u.Id,
    													Message__c = 'Test',
    													Active__c  = true,
    													Start_Time__c = System.now() - 1,
    													End_Time__c = System.now() + 1);
    	insert newOOO;												

    	Out_Of_Office__c duplicateOOO = new Out_Of_Office__c (user__c = u.Id);

		Database.SaveResult[] sr = Database.insert(new Out_Of_Office__c[] {duplicateOOO},false);
		
		System.assertEquals(sr[0].isSuccess(), false);
		
		System.runAs(u2)
		{
			FeedItem post = new FeedItem (ParentId = u.Id,
										  Body = 'test');
			insert post;
			
			post = [select id, (select id, CommentBody from FeedComments) from FeedItem where id = :post.Id];
			System.assertEquals(post.feedComments[0].CommentBody, 'Test');							  
		}
    }
}